name: rema
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.26.4
  - pandas=2.2.3
  - scikit-learn=1.4.2
  - ipykernel
  - pip
  - pip:
      - tensorflow-macos==2.15.0
      - tensorflow-metal
      - keras-tuner==1.4.7
      - matplotlib
      - seaborn
