name: rema
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.9
  - pandas=2.2.3
  - numpy=2.1.3
  - scikit-learn=1.6.1
  - tensorflow=2.19.0
  - keras-tuner=1.4.7
  - pip
  - pip:
      - matplotlib
      - seaborn
